version: '3'
services:
  localstack:
    image: localstack/localstack:0.11.2
    environment:
      - SERVICES=sqs,sns
    ports:
      - 4566:4566
      - 4571:4571
    volumes:
      - ./aws:/docker-entrypoint-initaws.d