name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle Wrapper
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build Distributable
        run: ./gradlew createDistributable

      - name: Zip Distributable Folder Linux
        if: runner.os != 'Windows'
        run: zip -r sr-sqs-${{ runner.os }}.zip build/compose/binaries/main/app

      - name: Zip Distributable Folder Windows
        if: runner.os == 'Windows'
        run: Compress-Archive -Path build\compose\binaries\main\app\* -DestinationPath sr-sqs-${{ runner.os }}.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sr-sqs-${{ runner.os }}.zip
          path: sr-sqs-${{ runner.os }}.zip

  upload-release:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest tag version
        id: get_tag
        run: |
          if git describe --tags --abbrev=0 2>/dev/null; then
            tag=$(git describe --tags --abbrev=0)
          else
            tag="v0.0.0"
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r -a parts <<< "${{ steps.get_tag.outputs.tag }}"
          major="${parts[0]#v}"
          minor="${parts[1]}"
          patch="${parts[2]}"
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Upload Release Assets
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.increment_version.outputs.new_version }}
          releaseName: 'Release ${{ steps.increment_version.outputs.new_version }}'
          artifacts: 'artifacts/*.zip'
